---
dist: xenial
# sudo: required
language: python
cache: pip
branches:
  only:
    - master
services:
  - docker
matrix:
  fast_finish: true
python:
  - "2.7"
  - "3.7"
env:
  - MOLECULE_PLAYBOOK=single_primary.yml SCENARIO_NAME=default
  - MOLECULE_PLAYBOOK=multi_primary.yml SCENARIO_NAME=default
  - MOLECULE_PLAYBOOK=default.yml SCENARIO_NAME=master_slave

before_script:
  - cd ../
  - mv ansible-role-mysql daixijun.mysql
  - cd daixijun.mysql

install:
  - pip install ansible molecule docker

script:
  - MOLECULE_PLAYBOOK=${MOLECULE_PLAYBOOK} molecule test --scenario-name=${SCENARIO_NAME}

notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
