---
- name: Ensure replication user
  mysql_user:
    name: "{{ mysql_repl_user | default('repl') }}"
    host: "%"
    password: "{{ mysql_repl_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    priv: "*.*:REPLICATION SLAVE"
    sql_log_bin: false
    state: present

- name: Change master
  shell: /usr/local/mysql/bin/mysql -uroot -p'{{ mysql_root_password }}' --socket={{ mysql_socket }} -ne "CHANGE MASTER TO MASTER_USER='repl', MASTER_PASSWORD='{{ mysql_repl_password }}' FOR CHANNEL 'group_replication_recovery';"
  no_log: yes
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Verify that the primary node status
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    query: "SELECT * FROM performance_schema.replication_group_members where member_role='PRIMARY';"
  run_once: true
  register: mysql_mgr_primary_status
  when: ansible_play_hosts.index(inventory_hostname) == 0
  tags:
    - skip_ansible_lint

- name: Initializing MGR cluster
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    query:
      - "SET GLOBAL group_replication_bootstrap_group=ON;"
      - "START GROUP_REPLICATION;"
      - "SET GLOBAL group_replication_bootstrap_group=OFF;"
  run_once: true
  when:
    - ansible_play_hosts.index(inventory_hostname) == 0
    - mysql_mgr_primary_status.rowcount[0]|int == 0
  tags:
    - skip_ansible_lint

- name: Verify that the member nodes status
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    query: SELECT * FROM performance_schema.replication_group_members where member_host='{{ hostvars[inventory_hostname]["ansible_"+mysql_interface].ipv4.address if mysql_interface else ansible_default_ipv4.address }}'
  register: mysql_mgr_member_status
  when:
    - ansible_play_hosts.index(inventory_hostname) != 0
  tags:
    - skip_ansible_lint

- name: Startting MGR cluster member nodes
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    query: "START GROUP_REPLICATION;"
  when:
    - ansible_play_hosts.index(inventory_hostname) != 0
    - mysql_mgr_member_status.rowcount[0]|int == 0
  tags:
    - skip_ansible_lint

- name: Query MGR Cluster status
  # shell: /usr/local/mysql/bin/mysql -uroot -p'{{ mysql_root_password }}' --socket={{ mysql_socket }} -ne "SELECT * FROM performance_schema.replication_group_members;"
  mysql_query:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    query: "SELECT * FROM performance_schema.replication_group_members;"
  run_once: true
  # register: mgr_cluster_status
  when:
    - ansible_play_hosts.index(inventory_hostname) == 0
  tags:
    - skip_ansible_lint

# - name: Show MGR Cluster status
#   debug:
#     msg: "{{ mgr_cluster_status.query_result[0] }}"
#   run_once: true
#   when:
#     - ansible_play_hosts.index(inventory_hostname) == 0
#     - mgr_cluster_status is not skipped

- name: Copy gr_member_routing_candidate_status.sql
  copy:
    src: gr_member_routing_candidate_status.sql
    dest: /tmp/gr_member_routing_candidate_status.sql
  run_once: true
  when:
    - ansible_play_hosts.index(inventory_hostname) == 0

- name: Create internal view sys.gr_member_routing_candidate_status for monitoring
  shell: /usr/local/mysql/bin/mysql -uroot -p'{{ mysql_root_password }}' --socket={{ mysql_socket }} < /tmp/gr_member_routing_candidate_status.sql
  no_log: yes
  run_once: true
  when:
    - ansible_play_hosts.index(inventory_hostname) == 0
    - mysql_initialize_status is not skipped

# FIXME: 模块对于mysql8.0以上的版本，给用户授权`ALL`权限的时候会出现幂等性问题
# 临时的解决方案是强制设置为 `changed_when: false`
- name: Ensure business users (MGR)
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('%') }}"
    password: "{{ item.password }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    state: "{{ item.state | default(omit) }}"
  run_once: true
  # changed_when: false
  no_log: yes
  loop: "{{ mysql_users }}"
  when:
    - ansible_play_hosts.index(inventory_hostname) == 0
    - mysql_users|length > 0
