---
- name: Create mysql certificate directory
  file:
    path: "{{ role_path }}/files/ssl"
    recurse: yes
    state: directory

- name: Generate an Self Signed OpenSSL CA private key
  openssl_privatekey:
    path: "{{ role_path }}/files/ssl/ca.key"
    type: RSA
    size: 2048

- name: Generate an Self Signed OpenSSL CA Certificate Signing Request
  openssl_csr:
    path: "{{ role_path }}/files/ssl/ca.csr"
    privatekey_path: "{{ role_path }}/files/ssl/ca.key"
    organization_name: mysql
    common_name: CertificateAuthority

- name: Generate a Self Signed OpenSSL CA certificate
  openssl_certificate:
    path: "{{ role_path }}/files/ssl/ca.crt"
    privatekey_path: "{{ role_path }}/files/ssl/ca.key"
    csr_path: "{{ role_path }}/files/ssl/ca.csr"
    selfsigned_not_after: "+3650d"
    provider: selfsigned

- name: Generate an Self Signed OpenSSL Server private key
  openssl_privatekey:
    path: "{{ role_path }}/files/ssl/server.key"
    type: RSA
    size: 2048

- name: Generate an Self Signed OpenSSL Server Certificate Signing Request
  openssl_csr:
    path: "{{ role_path }}/files/ssl/server.csr"
    privatekey_path: "{{ role_path }}/files/ssl/server.key"
    organization_name: mysql
    common_name: Server

- name: Generate a Self Signed OpenSSL Server certificate
  openssl_certificate:
    path: "{{ role_path }}/files/ssl/server.crt"
    ownca_path: "{{ role_path }}/files/ssl/ca.crt"
    ownca_privatekey_path: "{{ role_path }}/files/ssl/ca.key"
    csr_path: "{{ role_path }}/files/ssl/server.csr"
    selfsigned_not_after: "+3650d"
    provider: ownca
# - name: Set tls facts
#   set_fact:
#     mysql_ssl_ca: "{{ role_path }}/files/ssl/ca.crt"
#     mysql_ssl_cert: "{{ role_path }}/files/ssl/server.crt"
#     mysql_ssl_key: "{{ role_path }}/files/ssl/server.key"
