---
- name: Verify
  hosts: all
  become: true
  gather_facts: True
  any_errors_fatal: yes
  tasks:
    - name: Gather the rpm package facts
      package_facts:
        manager: rpm
      no_log: yes

    - name: Assert that the python2-PyMySQL package is installed
      assert:
        that:
          - "'python2-PyMySQL' in ansible_facts.packages"

    - name: Gather service facts
      service_facts:
      no_log: yes

    - name: Assert that the service state is running
      assert:
        that:
          - ansible_facts.services["mysqld.service"].state == "running"

    - name: Assert that the service status is enabled
      assert:
        that:
          - ansible_facts.services["mysqld.service"].status == "enabled"
      when:
        - ansible_virtualization_type != "docker"

    - name: Stat socket file
      stat:
        path: /var/run/mysqld/mysqld.sock
        get_checksum: no
      register: socket_stat
      no_log: yes

    - name: Assert that the socket file is in the expected state
      assert:
        that:
          - socket_stat.stat.exists
          - socket_stat.stat.issock
          - socket_stat.stat.mode == "0777"
          - socket_stat.stat.pw_name == "mysql"
          - socket_stat.stat.gr_name == "mysql"
    # - name: Gathers information about MySQL servers
    #   mysql_info:
    #   run_once: True
