---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mgr1
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    # purge_networks: false
    # network_mode: bridge
    # networks:
    #   - name: bridge
    #     ipv4_address: 172.17.0.3
    etc_hosts:
      mgr1: 172.17.0.2
      mgr2: 172.17.0.3
      mgr3: 172.17.0.4
  - name: mgr2
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
    # network_mode: bridge
    # networks:
    #   - name: bridge
    #     ipv4_address: 172.17.0.4
    etc_hosts:
      mgr1: 172.17.0.2
      mgr2: 172.17.0.3
      mgr3: 172.17.0.4
  - name: mgr3
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
    # network_mode: bridge
    # networks:
    #   - name: bridge
    #     ipv4_address: 172.17.0.5
    etc_hosts:
      mgr1: 172.17.0.2
      mgr2: 172.17.0.3
      mgr3: 172.17.0.4
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 159
