---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 --max-line-length=159 --ignore=E402
platforms:
  - name: mgr1
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: mgr2
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
  - name: mgr3
    image: geerlingguy/docker-centos7-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    purge_networks: false
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra
