---
- name: Converge
  hosts: all
  any_errors_fatal: yes
  roles:
    - role: daixijun.mysql
      mysql_remote_src: no
      mysql_group_replication_single_primary_mode: false
      # mysql_databases:
      #   - name: t1
      #     state: absent
      mysql_users:
        - name: monitor
          password: monitor
          priv: "sys.*:SELECT"
        - name: proxysql
          password: proxysql
          require_ssl: true
          priv: "*.*:INSERT,UPDATE,DELETE,SELECT,CREATE,DROP,ALTER"
          # state: absent
