---
name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: [single_primary, multi_primary, master_slave]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible "molecule[docker,lint]"
      - name: Test with molecule
        run: |
          cd ..
          cp -rf ansible-role-mysql daixijun.mysql
          cd daixijun.mysql
          molecule test --scenario-name ${{ matrix.scenario }}
      - name: Publish role to Galaxy
        if: success()
        run: |
          if [[ "${{ matrix.scenario }}" == "single_primary" ]]; then
            ansible-galaxy role import --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
          fi
